### ISSUE TITLE
Guru meditation while connecting to JBD device

### ISSUE THREAD

**Issue by sabakad** [BeaverUI/ESP32-BluetoothBMS2MQTT#3]
Hello,
I'm facing core crash during connection to JBD BLE device. (dump from serial line below). Anything I'm doing wrong or there is a bug in code? Thanks for advise

Connected
IP address: 192.168.2.228
Starting BLE... done
BLE is not connected, starting scanBLE: found Name: , Address: 34:7e:28:ae:72:90, manufacturer data: 0600010f20020fd24895f7235ed6736326347ebc9fbbb5bd5c4cef0684
BLE: found Name: , Address: 7b:33:8a:07:8d:de, manufacturer data: 4c0010073f1ff3e53cc138, txPower: 8
Scan finished.
Attempting MQTT connection...connected
Attempting MQTT connection...connected
Sending MQTT update
BLE is not connected, starting scanBLE: found Name: , Address: 34:7e:28:ae:72:90, manufacturer data: 0600010f20020fd24895f7235ed6736326347ebc9fbbb5bd5c4cef0684
BLE: found Name: xiaoxiang, Address: a4:c1:37:30:2b:74, manufacturer data: 742b3037c1a4, serviceUUID: 0000ff00-0000-1000-8000-00805f9b34fb
Forming a connection to a4:c1:37:30:2b:74
 - Connected to server
Guru Meditation Error: Core  0 panic'ed (Double exception). 

Core  0 register dump:
PC      : 0x400945a3  PS      : 0x00040536  A0      : 0x80135c5c  A1      : 0x3ffe17a0  
A2      : 0x3ffb6388  A3      : 0x3ffed11c  A4      : 0x3ffdbce8  A5      : 0x4010c904  
A6      : 0x007b6cc4  A7      : 0x003fffff  A8      : 0x40080080  A9      : 0x3ffe1890  
A10     : 0x00060736  A11     : 0x00040026  A12     : 0x0000180c  A13     : 0x00000001  
A14     : 0x00000004  A15     : 0x3ffb6cb0  SAR     : 0x00000008  EXCCAUSE: 0x00000002  
EXCVADDR: 0xffffffe0  LBEG    : 0x40091a28  LEND    : 0x40091a44  LCOUNT  : 0xffffffff  

Backtrace:0x400945a0:0x3ffe17a00x40135c59:0x3ffe17c0 0x400945a0:0x3ffe17e0 0x400945a0:0x3ffe1810 0x400945a0:0x3ffe1830 0x400945a0:0x3ffe1850 0x400945a0:0x3ffe1870 0x400945a0:0x3ffe1890 0x4008007d:0x3ffe17a0 0x4009947d:0x3ffe17c0 0x400945a0:0x3ffe17e0 0x400945a0:0x3ffe1810 0x400945a0:0x3ffe1830 0x400945a0:0x3ffe1850 0x400945a0:0x3ffe1870 0x400945a0:0x3ffe1890 0x4008007d:0x3ffe17a0 0x4009947d:0x3ffe17c0 0x400945a0:0x3ffe17e0 0x400945a0:0x3ffe1810 0x400945a0:0x3ffe1830 0x400945a0:0x3ffe1850 0x400945a0:0x3ffe1870 0x400945a0:0x3ffe1890 0x4008007d:0x3ffe17a0 0x4009947d:0x3ffe17c0 0x400945a0:0x3ffe17e0 0x400945a0:0x3ffe1810 0x400945a0:0x3ffe1830 0x400945a0:0x3ffe1850 0x400945a0:0x3ffe1870 0x400945a0:0x3ffe1890 0x4008007d:0x3ffe17a0 0x4009947d:0x3ffe17c0 0x400945a0:0x3ffe17e0 0x400945a0:0x3ffe1810 0x400945a0:0x3ffe1830 0x400945a0:0x3ffe1850 0x400945a0:0x3ffe1870 0x400945a0:0x3ffe1890 0x4008007d:0x3ffe17a0 0x4009947d:0x3ffe17c0 0x400945a0:0x3ffe17e0 0x400945a0:0x3ffe1810 0x400945a0:0x3ffe1830 0x400945a0:0x3ffe1850 0x400945a0:0x3ffe1870 0x400945a0:0x3ffe1890 0x4008007d:0x3ffe17a0 0x4009947d:0x3ffe17c0 0x400945a0:0x3ffe17e0 0x400945a0:0x3ffe1810 0x400945a0:0x3ffe1830 0x400945a0:0x3ffe1850 0x400945a0:0x3ffe1870 0x400945a0:0x3ffe1890 0x4008007d:0x3ffe17a0 0x4009947d:0x3ffe17c0 0x400945a0:0x3ffe17e0 0x400945a0:0x3ffe1810 0x400945a0:0x3ffe1830 0x400945a0:0x3ffe1850 0x400945a0:0x3ffe1870 0x400945a0:0x3ffe1890 0x4008007d:0x3ffe17a0 0x4009947d:0x3ffe17c0 0x400945a0:0x3ffe17e0 0x400945a0:0x3ffe1810 0x400945a0:0x3ffe1830 0x400945a0:0x3ffe1850 0x400945a0:0x3ffe1870 0x400945a0:0x3ffe1890 0x4008007d:0x3ffe17a0 0x4009947d:0x3ffe17c0 0x400945a0:0x3ffe17e0 0x400945a0:0x3ffe1810 0x400945a0:0x3ffe1830 0x400945a0:0x3ffe1850 0x400945a0:0x3ffe1870 0x400945a0:0x3ffe1890 0x4008007d:0x3ffe17a0 0x4009947d:0x3ffe17c0 0x400945a0:0x3ffe17e0 0x400945a0:0x3ffe1810 0x400945a0:0x3ffe1830 0x400945a0:0x3ffe1850 0x400945a0:0x3ffe1870 0x400945a0:0x3ffe1890 0x4008007d:0x3ffe17a0 0x4009947d:0x3ffe17c0 0x400945a0:0x3ffe17e0 0x400945a0:0x3ffe1810 0x400945a0:0x3ffe1830 0x400945a0:0x3ffe1850 0x400945a0:0x3ffe1870 0x400945a0:0x3ffe1890 0x4008007d:0x3ffe17a0 0x4009947d:0x3ffe17c0 0x400945a0:0x3ffe17e0 0x400945a0:0x3ffe1810 0x400945a0:0x3ffe1830  |<-CONTINUES

ELF file SHA256: 0000000000000000

Rebooting...
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:1344
load:0x40078000,len:13516
load:0x40080400,len:3604
entry 0x400805f0
E (297) psram: PSRAM ID read error: 0xffffffff

**Comment by BeaverUI** [comment]
Hi, thanks for posting. There is a bug somewhere, but I've been trying to find it for half a year and have no clue where to look. I have changed the Bluetooth library, tried various board library versions, have added as many debug points as possible, but still no clue.

What I have noticed is that, when the crash happens, the MQTT messages are also screwed up, so it looks like there is a memory leak somewhere, and I suspect the BLE stack. Any thoughts are very welcome, since it is an annoying issue.

**Comment by BeaverUI** [comment]
Addendum: my current thinking is that this has to do with the stack size of a RTOS task. I tried increasing it for the BLE task, but didn't help so far.

**Comment by sabakad** [comment]
Unfortunately not, still same issue:

ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:1184
load:0x40078000,len:12812
load:0x40080400,len:3032
entry 0x400805e4
E (323) psram: PSRAM ID read error: 0xffffffff
Attempting to connect to WiFi....
Connected
IP address: 192.168.2.228
Starting BLE... done
BLE is not connected, starting scanScan finished.
Attempting MQTT connection...connected
Sending MQTT update
17:53:02.343 -> Sending MQTT update
17:53:05.054 -> BLE is not connected, starting scanBLE: found Name: ,
Address: 43:b9:12:e2:88:27, manufacturer data: 4c001006411e84217fc2,
txPower: 12
17:53:05.142 -> BLE: found Name: , Address: 28:33:a7:e4:66:ad, manufacturer
data: 0600010f200233f3d0186466774ff3950e7ebe5c966326d01492418b54
17:53:05.142 -> BLE: found Name: xiaoxiang, Address: a4:c1:37:30:2b:74,
manufacturer data: 742b3037c1a4, serviceUUID:
0000ff00-0000-1000-8000-00805f9b34fb
17:53:05.269 -> Forming a connection to a4:c1:37:30:2b:74
17:53:05.664 ->  - Connected to server
17:53:06.330 -> Guru Meditation Error: Core  0 panic'ed (Double exception).
17:53:06.330 ->
17:53:06.330 -> Core  0 register dump:
17:53:06.330 -> PC      : 0x400945a3  PS      : 0x00040f36  A0      :
0x80134ab6  A1      : 0x3ffe1840
17:53:06.365 -> A2      : 0x00060133  A3      : 0x00040023  A4      :
0x00060120  A5      : 0x00060123
17:53:06.365 -> A6      : 0x00060123  A7      : 0x00000000  A8      :
0x00000001  A9      : 0x00000000
17:53:06.365 -> A10     : 0x00060123  A11     : 0x3ffe19b4  A12     :
0x00000268  A13     : 0x4010c934
17:53:06.365 -> A14     : 0x007b6c34  A15     : 0x003fffff  SAR     :
0x0000001c  EXCCAUSE: 0x00000002
17:53:06.415 -> EXCVADDR: 0x4010c924  LBEG    : 0x40091a28  LEND    :
0x40091a44  LCOUNT  : 0xffffffff
17:53:06.415 ->
17:53:06.415 ->
17:53:06.415 -> Backtrace:0x400945a0:0x3ffe18400x40134ab3:0x3ffe1850
0x400945a0:0x3ffe1870 0x400945a0:0x3ffe1890 0x400945a0:0x3ffe18b0
0x400945a0:0x3ffe18e0 0x400945a0:0x3ffe1900 0x4008007d:0x3ffe1950
0x4010c915:0x3ffe1980 0x40139788:0x3ffe19b0 0x4015d457:0x3ffe1c40
0x4013a73e:0x3ffe1ed0 0x4015d01d:0x3ffe1ef0 0x4013a73e:0x3ffe1f60
0x4015cc86:0x3ffe1f80 0x40139a99:0x3ffe1fa0 0x40139b05:0x3ffe2230
0x40139c46:0x3ffe2250 0x40125ae5:0x3ffe2270 0x40120e52:0x3ffe2510
0x401212fd:0x3ffe27a0 0x40121cb5:0x3ffe2800 0x40122ff0:0x3ffe2840
0x40123026:0x3ffe2860 0x4012e295:0x3ffe2880 0x4011ee0c:0x3ffe2a10
0x4013686f:0x3ffe2a30
17:53:06.458 ->
17:53:06.458 ->
17:53:06.458 ->
17:53:06.458 ->
17:53:06.458 -> ELF file SHA256: 0000000000000000
17:53:06.458 ->
17:53:06.458 -> Rebooting...

pá 1. 7. 2022 v 13:52 odesílatel BeaverUI ***@***.***> napsal:

**Comment by BeaverUI** [comment]
Are you able to make a connection to the BMS, or does it fail immediately? Because in the other cases I know, it gives this error after a while (minutes to days), but apart from that it works well.

**Comment by sabakad** [comment]
It just die during connection... :-(

pá 1. 7. 2022 v 18:01 odesílatel BeaverUI ***@***.***> napsal:

**Comment by BeaverUI** [comment]
Interesting. Can you do a traceback of the error? This might give me a hint on where the other error comes from as well.

**Comment by sabakad** [comment]
err, how would I do this in Arduino?

pá 1. 7. 2022 v 18:26 odesílatel BeaverUI ***@***.***> napsal:

**Comment by BeaverUI** [comment]
This plugin will do it for you: 
https://github.com/me-no-dev/EspExceptionDecoder

**Comment by BeaverUI** [comment]
Addendum: I just released some major update of the code. Please also check whether these updates fix your issues.

**Comment by BeaverUI** [comment]
If I backtrace your log with the current release, I get some weird backtraces, so probably our binary compiler output is different (e.g. different board selected, for example). I get these results (which I highly doubt are valid):
====
PC: 0x40083a52
EXCVADDR: 0x00000000

Decoding stack results
0x40083a4f: timer_arm_us_wrapper at /Users/ficeto/Desktop/ESP32/ESP32S2/esp32-arduino-lib-builder/esp-idf/components/esp_wifi/esp32/esp_adapter.c line 453
0x40083b6e: heap_caps_malloc_base at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/heap/heap_caps.c line 124
0x40130c13: l2cu_get_next_buffer_to_send at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/bt/host/bluedroid/stack/l2cap/l2c_utils.c line 3495
0x40108aed: timer_task at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/esp_timer/src/esp_timer.c line 349
0x40135930: config_new at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/bt/common/osi/config.c line 591
0x40159607: bta_dm_remname_cback at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/bt/host/bluedroid/bta/dm/bta_dm_act.c line 2834
0x401368e6: list_contains at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/bt/common/osi/list.c line 59
0x401591cd: bta_dm_set_eir at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/bt/host/bluedroid/bta/dm/bta_dm_act.c line 4155
0x401368e6: list_contains at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/bt/common/osi/list.c line 59
0x40158e36: bta_dm_disable_conn_down_timer_cback at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/bt/host/bluedroid/bta/dm/bta_dm_act.c line 3646
0x40135c41: config_save at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/bt/common/osi/config.c line 389
0x40135cad: config_save at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/bt/common/osi/config.c line 404
0x40135dee: config_save at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/bt/common/osi/config.c line 432
0x40121c51: gatt_process_read_by_type_rsp at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/bt/host/bluedroid/stack/gatt/gatt_cl.c line 844
0x4011cfbe: btm_sec_dev_rec_cback_event at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/bt/host/bluedroid/stack/btm/btm_sec.c line 5793
0x4011d469: btm_sec_encrypt_change at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/bt/host/bluedroid/stack/btm/btm_sec.c line 6043
0x4011de21: btm_sec_link_key_notification at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/bt/host/bluedroid/stack/btm/btm_sec.c line 4695
0x4011f15c: btu_hci_msg_process at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/bt/host/bluedroid/stack/btu/btu_task.c line 192
0x4011f192: btu_task_start_up at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/bt/host/bluedroid/stack/btu/btu_task.c line 261
0x4012a3f5: l2cble_process_sig_cmd at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/bt/host/bluedroid/stack/l2cap/l2c_ble.c line 753
0x4011af78: btm_sec_disconnect at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/bt/host/bluedroid/stack/btm/btm_sec.c line 4566
0x40132a17: smp_encrypt_data at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/bt/host/bluedroid/stack/smp/smp_keys.c line 162

====

Backtracing should be as simple as installing the plugin, building and re-programming the ESP, then paste the dump in the Exception Decoder. If decoding gives an error, probably the program code is not the same as the code running on the ESP.

**Comment by sabakad** [comment]
Hmm, I have Esp32 Dev module, but same guru meditation I've get even I compile this with ESP-Wrover one. For both cases I can't decode it via Exception Decoder.
Just summary of my env. - maybe you can see a difference from yours:
-Arduino 1.8.18
-1x ESP-32 Development Board 2.4GHz Dual-Mode WiFi+Bluetooth Antenna Module
-BMS: SP10S009-L8S-100A-B-U (8 cell 24v 100A BMS JBD)
-MQTT on RPI4 (Mosquitto)- >I've altered the code to accept different port and include UID and PWD that I have

I guess I will give up on this and go for RPI4 Jbdtool instead... ;-(

**Comment by sabakad** [comment]
Working, finally! I guess the problem was differend board manager url: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json I had  vs. https://dl.espressif.com/dl/package_esp32_index.json you've advised. Or simply complete Arduino env. reinstallation. Now all works flowlessly, thank you for your help!

**Comment by sabakad** [comment]
I guess I am facing this issue now.. After some time (few hours) it stops
updating mqtt server.
Seeing serial log it shows  '.......' like for connection to wifi. It is in
low wifi signal place, could this be the reason that script gets hung
because of it?
thx for help! Adam

pá 1. 7. 2022 v 18:01 odesílatel BeaverUI ***@***.***> napsal:

**Comment by BeaverUI** [comment]
The dots indicate it is trying to reconnect to WiFi, or waiting for the connection to come back to life. This is probably caused by your WiFi coverage. The antenna on the ESP is actually quite good, so if your cell phone has good coverage on the spot where the ESP is located, I think the ESP should have good range as well. There is an RSSI message send via MQTT that gives you the WiFi signal strength. Have a look at that number to get an idea of the signal quality, an RSSI above -75 dB or so (e.g. -70 dB ;-) ) should be fine.

Have you tried the latest version already?
