### ISSUE TITLE
MQTT Port and User

### ISSUE THREAD

**Issue by Kiki1904** [BeaverUI/ESP32-BluetoothBMS2MQTT#4]
Hi,

this is really nice work and I like it.
But I'm not really a programmer. I like to establish IoT environments and now I want to implement a battery with a JDB BMS.
So my question is: would it be possible to change the port of the MQTT-Server and maybe also add username and password?
This would be really great.

Thanks a lot

**Comment by BeaverUI** [comment]
Done! Please verify whether it works, as my mqtt broker doesn't have password protection.

**Comment by Kiki1904** [comment]
Hi!

Thanks for this quick reply. MQTT with username and password is working fine.
Maybe you can also add the opportunity to change the standard port?
No I do have the problem that the ESP can not connect to the BMS.
"BLE is not connected"
Sorry for so many questions.

**Comment by BeaverUI** [comment]
Did you set the correct name and IDs? Otherwise it will not find the BMS.

**Comment by Kiki1904** [comment]
I changed the name and the MAC address. Do I have to change the UUIDs?
Thanks!

**Comment by BeaverUI** [comment]
UUIDs should be OK, but you can check them using your phone (if you have an Android phone) with the BLE Scanner app.
